gemspec
gem 'corvid', path: '../../../..'

# golly-utils currently doesn't exist as a gem
cg= File.read(File.expand_path '../../../../../Gemfile', __FILE__).split(/\s*[\r\n]\s*/)
cg.select{|l| /^[^#]*golly-utils/ === l}.each{|l| eval l}
