gemspec
gem 'corvid', path: '../../../..'
gem 'golly-utils', git: 'git://github.com/japgolly/golly-utils.git' 
gem 'yard', git: 'git://github.com/japgolly/yard.git', branch: 'happy_days', group: :doc 
