source :rubygems
gemspec

gem 'corvid', path: '../../../..'

gem 'rake', group: :rake

group :test do
  gem 'ci_reporter', require: false
  gem 'simplecov', '>= 0.6.4', require: false
  gem 'guard', '>= 1.3.2', require: false
  gem 'rb-inotify', require: false
end

group :test_spec do
  gem 'rspec'
  gem 'guard-rspec', require: false
end

group :doc do
  gem 'yard'
  # Parsers for Markdown documentation
  gem 'rdiscount', platforms: :mri
  gem 'kramdown', platforms: :jruby
end

# vim:ft=ruby et ts=2 sw=2:

gem 'golly-utils', git: 'git://github.com/japgolly/golly-utils.git' # TODO use proper golly-utils
