require 'corvid/builtin/guard'

project_name  = Regexp.quote(determine_project_name)
rspec_options = read_rspec_options(File.dirname __FILE__)

ignore VIM_SWAP_FILES

########################################################################################################################
# test/spec

group :spec do
  guard 'rspec', binstubs: true, spec_paths: ['test/spec'], cli: rspec_options, all_on_start: false, all_after_pass: false do

    # Src files
    watch(%r'^lib/(.+)\.rb$')                 {|m| "test/spec/#{m[1]}_spec.rb"}
    watch(%r'^lib/#{project_name}/(.+)\.rb$') {|m| "test/spec/#{m[1]}_spec.rb"}

    # Each spec
    watch(%r'^test/spec/.+_spec\.rb$')

    if bulk?
      # Test stuff affecting everything
      watch(%r'^test/bootstrap/(?:all|spec).rb') {"test/spec"}
      watch(%r'^test/helpers/.+$')               {"test/spec"}
    end
  end
end

# vim:ft=ruby et ts=2 sw=2:
