# Load Corvid dependencies
eval File.read(File.expand_path '../.corvid/Gemfile', __FILE__)
gem 'golly-utils', git: 'git://github.com/japgolly/golly-utils.git' 
gem 'yard', git: 'git://github.com/japgolly/yard.git', branch: 'happy_days', group: :doc 
