# vim:ft=ruby et ts=2 sw=2:

gem 'corvid', path: '../../../..'

gem 'rake', group: :rake

group :test do
  gem 'ci_reporter', require: false
  gem 'simplecov', '>= 0.6.4', require: false
end if Dir.exists?('test')

group :test_unit do
  gem 'minitest'
  gem 'guard-minitest', '>= 0.5.0', require: false
  gem 'turn', '>= 0.9.4'
end if Dir.exists?('test/unit')

group :test_spec do
  gem 'rspec'
  gem 'guard-rspec', require: false
end if Dir.exists?('test/spec')

group :doc do
  gem 'yard'
end

group :debug do
  gem 'debugger', platforms: :mri
end
gem 'golly-utils', git: 'git://github.com/japgolly/golly-utils.git' # TODO use proper golly-utils

