source :rubygems

# Load Corvid dependencies
import File.expand_path('../.corvid/Gemfile', __FILE__)

# Parser for Markdown documentation
group :doc do
  gem 'rdiscount', platforms: :mri
  gem 'kramdown', platforms: :jruby
end

